cabal-version: 3.0

name:          at
version:       0.0.1.0
synopsis:      Effective Algebraic Topology
description:   See README.md
category:      Math
homepage:      https://github.com/mvr/at#readme
bug-reports:   https://github.com/mvr/at/issues
author:        Mitchell Riley
maintainer:    mitchell.v.riley@gmail.com
license:       BSD-3-Clause
license-file:  LICENSE
build-type:    Simple

extra-source-files:
  README.md

source-repository head
  type:     git
  location: https://github.com/mvr/at

common defaults
  default-language: Haskell2010
  default-extensions:
    DefaultSignatures
    DeriveFoldable
    DeriveFunctor
    DeriveTraversable
    DerivingVia
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTs
    GeneralizedNewtypeDeriving
    LambdaCase
    NoMonomorphismRestriction
    PolyKinds
    RankNTypes
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeFamilyDependencies
    TypeOperators
    UnicodeSyntax
    ViewPatterns
  build-depends:
    base >= 4.7 && < 5

library
  import: defaults
  hs-source-dirs: src
  exposed-modules:
    Control.Category.Constrained
    Math.Algebra.AbGroupPres
    Math.Algebra.AbGroupPres.IsoClass
    Math.Algebra.Bicomplex
    Math.Algebra.ChainComplex
    Math.Algebra.ChainComplex.Algebra
    Math.Algebra.ChainComplex.Algebra.Bar
    Math.Algebra.ChainComplex.Bicone
    Math.Algebra.ChainComplex.Coalgebra
    Math.Algebra.ChainComplex.Disk
    Math.Algebra.ChainComplex.DVF
    Math.Algebra.ChainComplex.Equivalence
    Math.Algebra.ChainComplex.Hom
    Math.Algebra.ChainComplex.Reduction
    Math.Algebra.ChainComplex.Shift
    Math.Algebra.ChainComplex.Sum
    Math.Algebra.ChainComplex.Tensor
    Math.Algebra.ChainComplex.TwistedTensor
    Math.Algebra.Combination
    Math.Algebra.Group
    Math.Algebra.SmithNormalForm
    Math.Topology.SGrp
    Math.Topology.SGrp.KGn
    Math.Topology.SGrp.KGn.Cocycle
    Math.Topology.SGrp.Wbar
    Math.Topology.SGrp.WbarDiscrete
    Math.Topology.SSet
    Math.Topology.SSet.DVF
    Math.Topology.SSet.Effective
    Math.Topology.SSet.Moore
    Math.Topology.SSet.NChains
    Math.Topology.SSet.NSimplex
    Math.Topology.SSet.Product
    Math.Topology.SSet.RPn
    Math.Topology.SSet.Skeleton
    Math.Topology.SSet.Sphere
    Math.Topology.SSet.TwistedProduct
    Math.Topology.SSet.Whitehead
    Math.ValueCategory
    Math.ValueCategory.Abelian
    Math.ValueCategory.Additive
  ghc-options:
    -Wall
    -Wno-name-shadowing
    -Wno-unused-matches
  build-depends:
    containers,
    matrix,
    mtl,
    vector

executable KZmod3_2
  import: defaults
  main-is: KZmod3_2.hs
  hs-source-dirs: examples
  ghc-options:
    -O2
    -main-is KZmod3_2
  build-depends:
    at,
    matrix,
    mtl,
    vector

executable Pi4S3
  import: defaults
  main-is: Pi4S3.hs
  hs-source-dirs: examples
  ghc-options:
    -O2
    -main-is Pi4S3
  build-depends:
    at,
    matrix,
    mtl,
    vector

executable Pi6S3
  import: defaults
  main-is: Pi6S3.hs
  hs-source-dirs: examples
  ghc-options:
    -O2
    -main-is Pi6S3
  build-depends:
    at,
    matrix,
    mtl,
    vector

test-suite spec
  import: defaults
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs: test
  other-modules:
    Math.Algebra.AbGroupPres.MatrixOpsSpec
    Math.Algebra.AbGroupPresSpec
    Math.Algebra.Bicomplex.Properties
    Math.Algebra.ChainComplex.Algebra.BarSpec
    Math.Algebra.ChainComplex.Algebra.Properties
    Math.Algebra.ChainComplex.BiconeSpec
    Math.Algebra.ChainComplex.DiskSpec
    Math.Algebra.ChainComplex.DVF.Properties
    Math.Algebra.ChainComplex.FundamentalCocycleSpec
    Math.Algebra.ChainComplex.HomSpec
    Math.Algebra.ChainComplex.Properties
    Math.Algebra.ChainComplex.Reduction.Properties
    Math.Algebra.ChainComplex.ShiftSpec
    Math.Algebra.ChainComplex.TensorSpec
    Math.Algebra.CombinationSpec
    Math.Algebra.SmithNormalFormSpec
    Math.Topology.SGrp.Properties
    Math.Topology.SGrp.KGnSpec
    Math.Topology.SGrp.WbarDiscreteSpec
    Math.Topology.SGrp.WbarSpec
    Math.Topology.SSetSpec
    Math.Topology.SSet.MooreSpec
    Math.Topology.SSet.Properties
    Math.Topology.SSet.ProductSpec
    Math.Topology.SSet.RPnSpec
    Math.Topology.SSet.SkeletonSpec
    Math.Topology.SSet.SphereSpec
    Math.Topology.SSet.TwistedProductSpec
    Math.Topology.SSet.WhiteheadSpec
    Math.ValueCategory.Abelian.Properties
    TestSupport.ArbitraryInstances
  ghc-options:
    -Wall
    -Wno-name-shadowing
    -Wno-unused-matches
  build-depends:
    at,
    hspec,
    matrix,
    QuickCheck,
    random,
    vector
