module Math.Algebra.ChainComplex.FundamentalCocycleSpec where

import Control.Monad (forM_)
import Data.List (sort)
import Test.Hspec

import qualified Math.Algebra.ChainComplex as CC
import Math.Algebra.ChainComplex.Sum
import Math.Algebra.Combination
import qualified Math.Topology.SSet.Moore as Moore
import Math.Topology.SSet.NChains
import qualified Math.Topology.SSet.Sphere as Sphere

-- The degree-two cycles are generated by L - R, and the degree-three
-- boundary is p(L - R), so H_2 is Z/p (with p = 0 meaning Z).
newtype SkewComplex = SkewComplex Int

data SkewBasis = Lower | L | R | Upper
  deriving (Eq, Ord, Show)

instance CC.ChainComplex SkewComplex where
  type Basis SkewComplex = SkewBasis

  degree _ Lower = 1
  degree _ L = 2
  degree _ R = 2
  degree _ Upper = 3

  diff (SkewComplex p) = CC.Morphism (-1) $ \b -> case b of
    Lower -> 0
    L -> singleComb Lower
    R -> singleComb Lower
    Upper -> Combination [(p, L), (-p, R)]

instance CC.FiniteType SkewComplex where
  basis _ 1 = [Lower]
  basis _ 2 = [L, R]
  basis _ 3 = [Upper]
  basis _ _ = []

cocycleValue :: CC.ChainComplex a => CC.FundamentalCocycle a -> CC.Chain a -> Int
cocycleValue cocycle chain = coeffOf (CC.cocycleMorphism cocycle `CC.onComb` chain) ()

expectCocycles :: CC.FiniteType a => a -> Int -> IO [CC.FundamentalCocycle a]
expectCocycles complex degree = case CC.fundamentalCocycles complex degree of
  Left err -> expectationFailure err >> pure []
  Right cocycles -> pure cocycles

spec :: Spec
spec = describe "fundamentalCocycles" $ do
  it "finds the integral fundamental class of a sphere" $ do
    cocycles <- expectCocycles (NChains (Sphere.Sphere 3)) 3
    case cocycles of
      [cocycle] -> do
        CC.cocycleOrder cocycle `shouldBe` Nothing
        CC.cocycleDegree cocycle `shouldBe` 3
        abs (cocycleValue cocycle (singleComb (BasisSimplex Sphere.Cell))) `shouldBe` 1
      _ -> expectationFailure "expected exactly one integral cocycle"

  it "finds the torsion fundamental class of a Moore space" $ do
    cocycles <- expectCocycles (NChains (Moore.Moore 2 2)) 2
    case cocycles of
      [cocycle] -> do
        CC.cocycleOrder cocycle `shouldBe` Just 2
        abs (cocycleValue cocycle (singleComb (BasisSimplex Moore.N))) `shouldBe` 1
      _ -> expectationFailure "expected exactly one order-two cocycle"

  it "returns no classes when the homology group is zero" $ do
    cocycles <- expectCocycles (SkewComplex 1) 2
    null cocycles `shouldBe` True

  it "returns no classes when the chain group is zero" $ do
    cocycles <- expectCocycles (SkewComplex 2) 0
    null cocycles `shouldBe` True

  it "extends an integral class from a non-coordinate cycle subgroup" $ do
    cocycles <- expectCocycles (SkewComplex 0) 2
    case cocycles of
      [cocycle] -> do
        CC.cocycleOrder cocycle `shouldBe` Nothing
        abs (cocycleValue cocycle (Combination [(1, L), (-1, R)])) `shouldBe` 1
        CC.cocycleMorphism cocycle `CC.onBasis` Lower `shouldBe` 0
        CC.cocycleMorphism cocycle `CC.onBasis` Upper `shouldBe` 0
      _ -> expectationFailure "expected exactly one integral cocycle"

  it "finds multiple torsion invariant factors and returns cocycles for them" $ do
    let complex = Sum (SkewComplex 2) (SkewComplex 4)
        cycleGenerators =
          [ Combination [(1, Left L), (-1, Left R)],
            Combination [(1, Right L), (-1, Right R)]
          ]
    cocycles <- expectCocycles complex 2
    sort (map CC.cocycleOrder cocycles) `shouldBe` [Just 2, Just 4]

    forM_ cocycles $ \cocycle -> case CC.cocycleOrder cocycle of
      Nothing -> expectationFailure "expected a torsion cocycle"
      Just order -> do
        forM_ (CC.basis complex 3) $ \b ->
          fromIntegral (cocycleValue cocycle (CC.diff complex `CC.onBasis` b)) `mod` order `shouldBe` 0
        foldl gcd order (map (fromIntegral . abs . cocycleValue cocycle) cycleGenerators) `shouldBe` 1
