module Math.Algebra.ChainComplex.FundamentalCocycleSpec where

import Control.Monad (forM_)
import Data.List (sort)
import Test.Hspec

import qualified Math.Algebra.ChainComplex as CC
import Math.Algebra.ChainComplex.Sum
import Math.Algebra.Combination
import Math.Algebra.Group
import qualified Math.Topology.SSet.Moore as Moore
import Math.Topology.SSet.NChains
import qualified Math.Topology.SSet.Sphere as Sphere

-- The degree-two cycles are generated by L - R, and the degree-three
-- boundary is p(L - R), so H_2 is Z/p (with p = 0 meaning Z).
newtype SkewComplex = SkewComplex Int

data SkewBasis = Lower | L | R | Upper
  deriving (Eq, Ord, Show)

instance CC.ChainComplex SkewComplex where
  type Basis SkewComplex = SkewBasis

  degree _ Lower = 1
  degree _ L = 2
  degree _ R = 2
  degree _ Upper = 3

  diff (SkewComplex p) = CC.Morphism (-1) $ \b -> case b of
    Lower -> 0
    L -> singleComb Lower
    R -> singleComb Lower
    Upper -> fromTerms [(p, L), (-p, R)]

instance CC.FiniteType SkewComplex where
  basis _ 1 = [Lower]
  basis _ 2 = [L, R]
  basis _ 3 = [Upper]
  basis _ _ = []

expectCocycles :: CC.FiniteType a => a -> Int -> IO [CC.FundamentalCocycle a]
expectCocycles complex degree = pure $ CC.fundamentalCocycles complex degree

spec :: Spec
spec = do
  describe "Cochain" $
    it "extends basis values linearly over the coefficient group" $ do
      let c = Zmod 5
          cochain :: CC.Cochain SkewComplex Zmod
          cochain = CC.Cochain 2 $ \x -> case x of
            L -> zmodElement c (2 :: Integer)
            R -> zmodElement c (4 :: Integer)
            _ -> unit c
      CC.cochainOnChain c cochain (fromTerms [(3, L), (-2, R)])
        `shouldBe` zmodElement c (-2 :: Integer)

  describe "Cocycle" $ do
    it "pulls back along a chain map" $ do
      let cocycle = CC.Cocycle $ CC.Cochain 2 $ \x -> case x of
            BasisSimplex Sphere.Cell -> 1
            _ -> 0
          doubling = CC.Morphism 0 $ \x -> 2 .* singleComb x
          pulledBack = CC.pullbackCocycle Z doubling cocycle
      CC.cocycleOnBasis pulledBack (BasisSimplex Sphere.Cell)
        `shouldBe` 2

    it "accepts a cochain that vanishes on boundaries" $ do
      let cochain = CC.Cochain 2 $ \x -> case x of
            BasisSimplex Sphere.Cell -> 1
            _ -> 0
      case CC.mkCocycle (NChains (Sphere.Sphere 2)) Z cochain of
        Just _ -> pure ()
        Nothing -> expectationFailure "expected a cocycle"

    it "rejects a cochain that does not vanish on boundaries" $ do
      let cochain = CC.Cochain 2 $ \x -> case x of
            BasisSimplex Moore.N -> 1
            _ -> 0
      case CC.mkCocycle (NChains (Moore.Moore 2 2)) Z cochain of
        Nothing -> pure ()
        Just _ -> expectationFailure "expected a non-cocycle"

  describe "FundamentalCocycle" $
    it "pulls back along a chain map" $ do
      let cocycle :: CC.FundamentalCocycle (NChains Sphere.Sphere)
          cocycle = CC.IntegralFundamentalCocycle $ CC.Cocycle $ CC.Cochain 2 $ \x -> case x of
            BasisSimplex Sphere.Cell -> 1
            _ -> 0
          doubling :: CC.Morphism (NChains Sphere.Sphere) (NChains Sphere.Sphere)
          doubling = CC.Morphism 0 $ \x -> 2 .* singleComb x
          pulledBack = CC.pullbackFundamentalCocycle doubling cocycle
      case pulledBack of
        CC.IntegralFundamentalCocycle c ->
          CC.cocycleOnBasis c (BasisSimplex Sphere.Cell) `shouldBe` 2
        CC.ModularFundamentalCocycle _ _ ->
          expectationFailure "expected an integral cocycle"

  fundamentalCocycleSpec

fundamentalCocycleSpec :: Spec
fundamentalCocycleSpec = describe "fundamentalCocycles" $ do
  it "finds the integral fundamental class of a sphere" $ do
    cocycles <- expectCocycles (NChains (Sphere.Sphere 3)) 3
    case cocycles of
      [fundamental@(CC.IntegralFundamentalCocycle cocycle)] -> do
        CC.fundamentalCocycleDegree fundamental `shouldBe` 3
        abs (CC.cocycleOnChain Z cocycle (singleComb (BasisSimplex Sphere.Cell)))
          `shouldBe` 1
      _ -> expectationFailure "expected exactly one integral cocycle"

  it "finds the torsion fundamental class of a Moore space" $ do
    cocycles <- expectCocycles (NChains (Moore.Moore 2 2)) 2
    case cocycles of
      [CC.ModularFundamentalCocycle c@(Zmod 2) cocycle] ->
        CC.cocycleOnChain c cocycle (singleComb (BasisSimplex Moore.N))
          `shouldBe` zmodElement c (1 :: Integer)
      _ -> expectationFailure "expected exactly one order-two cocycle"

  it "returns no classes when the homology group is zero" $ do
    cocycles <- expectCocycles (SkewComplex 1) 2
    null cocycles `shouldBe` True

  it "returns no classes when the chain group is zero" $ do
    cocycles <- expectCocycles (SkewComplex 2) 0
    null cocycles `shouldBe` True

  it "extends an integral class from a non-coordinate cycle subgroup" $ do
    cocycles <- expectCocycles (SkewComplex 0) 2
    case cocycles of
      [CC.IntegralFundamentalCocycle cocycle] -> do
        abs (CC.cocycleOnChain Z cocycle (fromTerms [(1, L), (-1, R)]))
          `shouldBe` 1
        CC.cocycleOnBasis cocycle Lower `shouldBe` 0
        CC.cocycleOnBasis cocycle Upper `shouldBe` 0
      _ -> expectationFailure "expected exactly one integral cocycle"

  it "finds multiple torsion invariant factors and returns cocycles for them" $ do
    let complex = Sum (SkewComplex 2) (SkewComplex 4)
        cycleGenerators =
          [ fromTerms [(1, Left L), (-1, Left R)],
            fromTerms [(1, Right L), (-1, Right R)]
          ]
    cocycles <- expectCocycles complex 2
    let orders = [order | CC.ModularFundamentalCocycle (Zmod order) _ <- cocycles]
    sort orders `shouldBe` [2, 4]

    forM_ cocycles $ \fundamental -> case fundamental of
      CC.IntegralFundamentalCocycle _ ->
        expectationFailure "expected a torsion cocycle"
      CC.ModularFundamentalCocycle c@(Zmod order) cocycle -> do
        forM_ (CC.basis complex 3) $ \b ->
          CC.cocycleOnChain c cocycle (CC.diff complex `CC.onBasis` b)
            `shouldBe` unit c
        let values =
              [ value
              | generator <- cycleGenerators,
                let ZmodElement value = CC.cocycleOnChain c cocycle generator
              ]
        foldl gcd order values `shouldBe` 1
