{-# LANGUAGE UndecidableInstances #-}

-- | Chain complex of free \(ℤ\)-modules
module Math.Algebra.ChainComplex where

import Control.Category.Constrained (id, (.))
import qualified Control.Category.Constrained as Constrained
import Control.Exception (evaluate)
import Data.IORef
import qualified Data.Map.Strict as Map
import qualified Data.Matrix as M
import Data.Maybe (fromJust)
import qualified Data.Vector as V
import System.IO.Unsafe (unsafePerformIO)
import Prelude hiding (id, return, (.))

import Math.Algebra.AbGroupPres
import Math.Algebra.Combination
import Math.Algebra.Group
import Math.Algebra.SmithNormalForm
import Math.ValueCategory (Arrow, mor)
import Math.ValueCategory.Abelian

class Ord (Basis a) => ChainComplex a where
  type Basis a

  isBasis :: a -> Basis a -> Bool
  isBasis _ _ = True

  degree :: a -> Basis a -> Int
  diff :: a -> Morphism a a

-- | A chain complex with a known lower bound on the degrees of its basis
-- elements.
class ChainComplex a => BoundedBelow a where
  lowerBound :: a -> Int

-- | A non-negatively graded chain complex whose degree-zero group is
-- canonically generated by one element.
class BoundedBelow a => ConnectedChainComplex a

-- | A connected chain complex whose degree-one group is zero.
class ConnectedChainComplex a => OneReducedChainComplex a

type Chain a = Combination (Basis a)

instance ChainComplex () where
  type Basis () = ()
  degree _ _ = 0
  diff _ = morphismZeroOfDeg (-1)

instance BoundedBelow () where
  lowerBound _ = 0

instance ConnectedChainComplex ()

instance OneReducedChainComplex ()

class ChainComplex a => FiniteType a where
  dim :: a -> Int -> Int
  dim a i = length (basis a i)
  -- * `all isSimplex (basis n)`
  basis :: a -> Int -> [Basis a]

instance FiniteType () where
  dim _ 0 = 1
  dim _ _ = 0
  basis _ 0 = [()]
  basis _ _ = []

validComb :: ChainComplex a => a -> Chain a -> Bool
validComb a combination = and $ fmap (\(_, b) -> isBasis a b) (coeffs combination)

-- well, not really
kozulRule :: Num b => Int -> b -> b
kozulRule n c = if even n then c else negate c

-- | A homogeneous morphism between chain complexes.
data Morphism a b = Morphism
  { morphismDegree :: Int,
    onBasis :: Basis a -> Combination (Basis b)
  }

-- | Retag a morphism with unchanged endpoint basis types.
sameBasisMorphism ::
  (Basis a ~ Basis a', Basis b ~ Basis b') =>
  Morphism a b ->
  Morphism a' b'
sameBasisMorphism (Morphism morphismDegree action) =
  Morphism morphismDegree action

-- | Identity morphism between complexes with the same basis type.
sameBasisId ::
  Basis a ~ Basis b =>
  Morphism a b
sameBasisId = Morphism 0 singleComb

-- | Memoise a pure function for the lifetime of the returned closure.
--
-- The algorithms in this package build large morphisms out of recursive
-- contractions.  Those contractions describe DAGs, but evaluating them as
-- ordinary functions expands the DAG into a tree.  This helper lets the
-- recursive morphisms retain one result per visited basis element instead.
memoiseOrd :: Ord a => (a -> b) -> a -> b
memoiseOrd f = unsafePerformIO $ do
  cache <- newIORef Map.empty
  pure $ \key -> unsafePerformIO $ do
    current <- readIORef cache
    case Map.lookup key current of
      Just value -> pure value
      Nothing -> do
        value <- evaluate (f key)
        atomicModifyIORef' cache $ \latest ->
          case Map.insertLookupWithKey (\_ _ existing -> existing) key value latest of
            (Just existing, updated) -> (updated, existing)
            (Nothing, updated) -> (updated, value)
{-# NOINLINE memoiseOrd #-}

-- | Retain the image of each visited source basis element.
memoiseMorphism :: ChainComplex a => Morphism a b -> Morphism a b
memoiseMorphism (Morphism morphismDegree action) =
  Morphism morphismDegree (memoiseOrd action)

onComb :: ChainComplex b => Morphism a b -> Chain a -> Chain b
onComb m combination = bindCombination combination (m `onBasis`)

morphismZeroOfDeg :: Int -> Morphism a b
morphismZeroOfDeg d = Morphism d (const zeroCombination)

-- | Extend a function on basis representations to a degree-zero morphism.
basisMorphism ::
  (Basis a -> Basis b) ->
  Morphism a b
basisMorphism f = Morphism 0 (singleComb . f)

instance Show (Morphism a b) where
  -- TODO
  show (Morphism d f) = "Morphism of degree " ++ show d

instance Constrained.Semigroupoid Morphism where
  type Object Morphism a = ChainComplex a

  (Morphism d2 f2) . (Morphism d1 f1) =
    Morphism (d1 + d2) (\basis -> bindCombination (f1 basis) f2)

instance Constrained.Category Morphism where
  id = Morphism 0 singleComb

instance (ChainComplex a, ChainComplex b) => Num (Morphism a b) where
  fromInteger 0 = morphismZeroOfDeg 0
  fromInteger _ = error "Morphism: fromInteger"

  (Morphism d1 f1) + (Morphism _ f2) = Morphism d1 (\x -> f1 x + f2 x)
  negate (Morphism d f) = Morphism d (negate . f)

  (*) = error "Morphism: (*)"
  abs = error "Morphism: abs"
  signum = error "Morphism: signum"

-- | A `ClosedMorphism` is a morphism that includes the data of its
-- endpoints. (Closed as in a closed interval.) We cannot define id,
-- because we would need the data of `a`.
data ClosedMorphism a b = ClosedMorphism a (Morphism a b) b

instance Constrained.Semigroupoid ClosedMorphism where
  type Object ClosedMorphism o = ChainComplex o
  (ClosedMorphism _ n c) . (ClosedMorphism a m _) = ClosedMorphism a (n . m) c

data ChainGroup a = ChainGroup Int a
newtype ChainGroupElt a = ChainGroupElt (Chain a)

instance (ChainComplex a) => Group (ChainGroup a) where
  type Element (ChainGroup a) = ChainGroupElt a
  prod _ (ChainGroupElt left) (ChainGroupElt right) =
    ChainGroupElt (left + right)
  inv _ (ChainGroupElt chain) = ChainGroupElt (negate chain)
  unit _ = ChainGroupElt 0

toChainGrpElt :: (FiniteType a) => a -> Int -> Chain a -> AbGroupPresElt
toChainGrpElt a n cs = AbGroupPresElt $ M.fromList 1 (length r) (fmap (fromIntegral . coeffOf cs) r)
  where
    r = basis a n

fromChainGrpElt :: (FiniteType a) => a -> Int -> AbGroupPresElt -> Chain a
fromChainGrpElt a n (AbGroupPresElt m) =
  fromTerms $ zip (fromIntegral <$> M.toList m) (basis a n)

chainGroup :: FiniteType a => a -> Int -> AbGroupPres
chainGroup a n = freeAbGroup (fromIntegral (dim a n))

chainDiff :: FiniteType a => a -> Int -> Arrow AbGroupPres
chainDiff a n = morphismFromFullMatrix (chainGroup a n) (chainGroup a (n - 1)) (M.matrix rows cols findCoef)
  where
    rows = dim a (n - 1)
    cols = dim a n
    codbasis = basis a (n - 1)
    dombasis = basis a n
    images = fmap (onBasis (diff a)) dombasis
    findCoef (i, j) = fromIntegral $ coeffOf (images !! (j - 1)) (codbasis !! (i - 1))

chainDiffs :: FiniteType a => a -> [Arrow AbGroupPres]
chainDiffs a = fmap (chainDiff a) [0 ..]

-- Only compute the group presentation once
data HomologyGroup a = HomologyGroup Int AbGroupPres a

instance Show a => Show (HomologyGroup a) where
  show (HomologyGroup n p a) = "H^" ++ show n ++ "(" ++ show a ++ ")=" ++ show p

newtype HomologyClass a = HomologyClass (Chain a)

instance Show (Basis a) => Show (HomologyClass a) where
  show (HomologyClass cs) = show cs

classRepresentative :: HomologyClass a -> Chain a
classRepresentative (HomologyClass cs) = cs

instance (FiniteType a) => Group (HomologyGroup a) where
  type Element (HomologyGroup a) = HomologyClass a
  prod (HomologyGroup n p a) (HomologyClass x) (HomologyClass y) = HomologyClass $ fromChainGrpElt a n $ prod p (toChainGrpElt a n x) (toChainGrpElt a n y)
  inv (HomologyGroup n p a) (HomologyClass x) = HomologyClass $ fromChainGrpElt a n $ inv p (toChainGrpElt a n x)
  unit (HomologyGroup n p a) = HomologyClass $ fromChainGrpElt a n (unit p)

homologyGenerators :: FiniteType a => HomologyGroup a -> [HomologyClass a]
homologyGenerators (HomologyGroup n p a) = fmap HomologyClass chains
  where
    chains = fmap (fromChainGrpElt a n . AbGroupPresElt . (fromReduced p *) . eltVector) (indGenerators p)

homologies :: FiniteType a => a -> [AbGroupPres]
homologies a = fmap (uncurry homology) pairs
  where
    diffs = chainDiffs a
    pairs = zip (drop 1 diffs) diffs

homologyGroups :: FiniteType a => a -> [HomologyGroup a]
homologyGroups a = fmap (\(n, f, g) -> HomologyGroup n (homology f g) a) pairs
  where
    diffs = chainDiffs a
    pairs = zip3 [0 ..] (drop 1 diffs) diffs

-- | A (not necessarily Z-valued) cochain, defined by its values on a chain basis.
data Cochain a c = Cochain
  { cochainDegree :: !Int,
    cochainOnBasis :: Basis a -> Element c
  }

-- | Extend a cochain linearly to arbitrary chains.
cochainOnChain :: Abelian c => c -> Cochain a c -> Chain a -> Element c
cochainOnChain c (Cochain _ f) chain =
  foldl' addTerm (unit c) (coeffs chain)
  where
    addTerm total (a, x) =
      prod c total $
        scale c (fromIntegral a) (f x)

-- | A cochain known to vanish on boundaries.
newtype Cocycle a c = Cocycle
  { cocycleCochain :: Cochain a c
  }

-- | Check the cocycle condition in the one degree that can contribute to
-- the coboundary.
mkCocycle ::
  (FiniteType a, Abelian c, Eq (Element c)) =>
  a ->
  c ->
  Cochain a c ->
  Maybe (Cocycle a c)
mkCocycle a c cochain@(Cochain n _)
  | n < 0 = Nothing
  | all vanishesOnBoundary (basis a (n + 1)) = Just (Cocycle cochain)
  | otherwise = Nothing
  where
    vanishesOnBoundary x =
      cochainOnChain c cochain (diff a `onBasis` x) == unit c

cocycleDegree :: Cocycle a c -> Int
cocycleDegree (Cocycle (Cochain n _)) = n

cocycleOnBasis :: Cocycle a c -> Basis a -> Element c
cocycleOnBasis (Cocycle (Cochain _ f)) = f

cocycleOnChain :: Abelian c => c -> Cocycle a c -> Chain a -> Element c
cocycleOnChain c (Cocycle cochain) = cochainOnChain c cochain

-- | Pull a cocycle back along a chain map.
pullbackCocycle :: Abelian c => c -> Morphism a b -> Cocycle b c -> Cocycle a c
pullbackCocycle c (Morphism d f) (Cocycle cochain@(Cochain n _)) =
  Cocycle $ Cochain (n - d) $ \x -> cochainOnChain c cochain (f x)

-- | A fundamental cohomology class associated to a cyclic summand of a
-- homology group, with coefficients in that summand.
data FundamentalCocycle a
  = IntegralFundamentalCocycle (Cocycle a Z)
  | ModularFundamentalCocycle Zmod (Cocycle a Zmod)

-- | Degree in which the fundamental cocycle is supported.
fundamentalCocycleDegree :: FundamentalCocycle a -> Int
fundamentalCocycleDegree (IntegralFundamentalCocycle cocycle) =
  cocycleDegree cocycle
fundamentalCocycleDegree (ModularFundamentalCocycle _ cocycle) =
  cocycleDegree cocycle

-- | Pull a fundamental cocycle back along a chain map.
pullbackFundamentalCocycle ::
  Morphism a b ->
  FundamentalCocycle b ->
  FundamentalCocycle a
pullbackFundamentalCocycle f (IntegralFundamentalCocycle cocycle) =
  IntegralFundamentalCocycle (pullbackCocycle Z f cocycle)
pullbackFundamentalCocycle f (ModularFundamentalCocycle c cocycle) =
  ModularFundamentalCocycle c (pullbackCocycle c f cocycle)

-- | Fundamental cocycles for the cyclic invariant factors of H_n(a).
fundamentalCocycles :: FiniteType a => a -> Int -> [FundamentalCocycle a]
fundamentalCocycles a n =
  fundamentalCocyclesWithDiffs a n (chainDiff a n) (chainDiff a (n + 1))

-- | As 'fundamentalCocycles', but reuse the supplied differentials.  The
-- arrows are expected to be \(d_n\) and \(d_{n+1}\), respectively.
fundamentalCocyclesWithDiffs ::
  FiniteType a =>
  a ->
  Int ->
  Arrow AbGroupPres ->
  Arrow AbGroupPres ->
  [FundamentalCocycle a]
fundamentalCocyclesWithDiffs a n outgoing incoming = fmap (makeCocycle leftChange) nontrivialRows
  where
    cycles = matrixKernel (fullMorphism (mor outgoing))
    boundaries = fullMorphism (mor incoming)
    boundaryCoordinates = fromJust $ solveMatrix cycles boundaries

    Triple leftChange _ smith _ _ = smithNormalForm boundaryCoordinates
    diagonal = take cycleRank $ V.toList (M.getDiag smith) ++ repeat 0
    nontrivialRows = filter ((/= 1) . snd) $ zip [1 ..] diagonal

    cycleRank = M.ncols cycles

    makeCocycle leftChange (i, order) =
      let cycleValues = M.fromList cycleRank 1 (V.toList (M.getRow i leftChange))
          functional = fromJust $ solveMatrix (M.transpose cycles) cycleValues
          functionalValues = zip (basis a n) (M.toList functional)
          integerValue b
            | degree a b /= n = 0
            | otherwise = fromJust $ lookup b functionalValues
       in if order == 0
            then IntegralFundamentalCocycle $ Cocycle (Cochain n integerValue)
            else
              let c = Zmod (fromIntegral order)
               in ModularFundamentalCocycle c $
                    Cocycle (Cochain n (zmodElement c . integerValue))

neghomologies :: FiniteType a => a -> [AbGroupPres]
neghomologies a = fmap (uncurry homology) pairs
  where
    diffs = fmap (chainDiff a . negate) [-1 ..]
    pairs = zip diffs (drop 1 diffs)
